---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-operator-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vault-operator-clusterrole
rules:
- apiGroups: ["tuananh.net"]
  resources: ["customresourcedefinitions"]
  resourceNames: ["vaultsecrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: controll-demo-sa-cluster-admin-binding
roleRef:
  apiGroup: ""
  kind: ClusterRole
  name: vault-operator-clusterrole
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: vault-operator-sa
    namespace: default
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: vault-operator
  name: vault-operator
spec:
  serviceAccountName: vault-operator-sa
  automountServiceAccountToken: true
  containers:
    - image: tuananh/vault-operator
      name: vault-operator
      imagePullPolicy: IfNotPresent
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always