name: CI
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: ">=1.17.0"
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
          ~/go/bin/
          ~/.kubebuilder/bin/k8s
        key: ${{ runner.os }}-go-cache-${{ hashFiles('**/go.sum') }}
    - name: CI - Verifications and Tests
      run: |
        make setup-ci-env
        make validate-ci